import { PDFDocument, PDFPage, rgb, StandardFonts } from 'pdf-lib'
import fontkit from '@pdf-lib/fontkit'

interface CustodyEntry {
  officer: string
  timestamp: string
  action: string
  ipfsCid: string
  notes?: string
  location?: string
}

interface EvidenceDetails {
  id: string
  title: string
  description: string
  filename: string
  fileHash: string
  ipfsCid: string
  collectedBy: string
  collectedAt: string
  location?: string
  custodyChain: CustodyEntry[]
}

interface CaseDetails {
  id: string
  title: string
  caseNumber: string
  status: string
  priority: string
  createdAt: string
  createdBy: {
    name: string
    email: string
  }
}

interface CustodyReportData {
  evidence: EvidenceDetails
  case: CaseDetails
  merkleRoot?: string
  generatedAt: string
  generatedBy: {
    name: string
    email: string
  }
}

export class CustodyChainPDFGenerator {
  private doc!: PDFDocument
  private currentPage!: PDFPage
  private yPosition!: number
  private pageWidth!: number
  private pageHeight!: number
  private margin: number
  private titleFont!: any
  private bodyFont!: any
  private boldFont!: any

  constructor() {
    this.margin = 50
    this.yPosition = 750
  }

  async initializePDF(): Promise<void> {
    this.doc = await PDFDocument.create()
    this.doc.registerFontkit(fontkit)

    // Load standard fonts
    this.titleFont = await this.doc.embedFont(StandardFonts.HelveticaBold)
    this.bodyFont = await this.doc.embedFont(StandardFonts.Helvetica)
    this.boldFont = await this.doc.embedFont(StandardFonts.HelveticaBold)

    this.currentPage = this.doc.addPage()
    this.pageWidth = this.currentPage.getWidth()
    this.pageHeight = this.currentPage.getHeight()
    this.yPosition = this.pageHeight - this.margin
  }

  private addNewPage(): void {
    this.currentPage = this.doc.addPage()
    this.yPosition = this.pageHeight - this.margin
    this.addPageFooter()
  }

  private addPageFooter(): void {
    const pageCount = this.doc.getPages().length
    this.currentPage.drawText(
      `Page ${pageCount} - Generated by ChainGuard Evidence Platform`,
      {
        x: this.margin,
        y: 30,
        size: 8,
        font: this.bodyFont,
        color: rgb(0.5, 0.5, 0.5)
      }
    )
  }

  private checkPageSpace(requiredSpace: number): void {
    if (this.yPosition - requiredSpace < this.margin + 50) {
      this.addNewPage()
    }
  }

  private drawHeader(data: CustodyReportData): void {
    // Official Header
    this.currentPage.drawText('CHAINGUARD EVIDENCE PLATFORM', {
      x: this.margin,
      y: this.yPosition,
      size: 20,
      font: this.titleFont,
      color: rgb(0.1, 0.2, 0.5)
    })

    this.yPosition -= 25

    this.currentPage.drawText('OFFICIAL CHAIN OF CUSTODY REPORT', {
      x: this.margin,
      y: this.yPosition,
      size: 16,
      font: this.boldFont,
      color: rgb(0, 0, 0)
    })

    this.yPosition -= 35

    // Case Information Box
    this.currentPage.drawRectangle({
      x: this.margin,
      y: this.yPosition - 80,
      width: this.pageWidth - (this.margin * 2),
      height: 80,
      borderColor: rgb(0.1, 0.2, 0.5),
      borderWidth: 1
    })

    this.yPosition -= 15

    // Case details
    const caseInfo = [
      `Case Number: ${data.case.id}`,
      `Case Title: ${data.case.title}`,
      `Status: ${data.case.status}`,
      `Priority: ${data.case.priority}`,
      `Created: ${new Date(data.case.createdAt).toLocaleString()}`
    ]

    caseInfo.forEach((info) => {
      this.currentPage.drawText(info, {
        x: this.margin + 10,
        y: this.yPosition,
        size: 10,
        font: this.bodyFont
      })
      this.yPosition -= 12
    })

    this.yPosition -= 25
  }

  private drawEvidenceDetails(data: CustodyReportData): void {
    this.checkPageSpace(120)

    this.currentPage.drawText('EVIDENCE DETAILS', {
      x: this.margin,
      y: this.yPosition,
      size: 14,
      font: this.boldFont
    })

    this.yPosition -= 20

    // Evidence details box
    this.currentPage.drawRectangle({
      x: this.margin,
      y: this.yPosition - 90,
      width: this.pageWidth - (this.margin * 2),
      height: 90,
      borderColor: rgb(0.7, 0.7, 0.7),
      borderWidth: 1
    })

    this.yPosition -= 15

    const evidenceInfo = [
      `Evidence ID: ${data.evidence.id}`,
      `Filename: ${data.evidence.filename}`,
      `Description: ${data.evidence.description}`,
      `File Hash (SHA-256): ${data.evidence.fileHash}`,
      `IPFS CID: ${data.evidence.ipfsCid}`,
      `Initial Collection: ${new Date(data.evidence.collectedAt).toLocaleString()} by ${data.evidence.collectedBy}`
    ]

    evidenceInfo.forEach((info) => {
      this.currentPage.drawText(info, {
        x: this.margin + 10,
        y: this.yPosition,
        size: 9,
        font: this.bodyFont
      })
      this.yPosition -= 12
    })

    this.yPosition -= 25
  }

  private drawCustodyChainTable(data: CustodyReportData): void {
    this.checkPageSpace(150)

    this.currentPage.drawText('CUSTODY CHAIN TIMELINE', {
      x: this.margin,
      y: this.yPosition,
      size: 14,
      font: this.boldFont
    })

    this.yPosition -= 30

    // Table headers
    const tableHeaders = ['Date/Time', 'Officer', 'Action', 'Location', 'Notes']
    const columnWidths = [120, 120, 100, 100, 160]
    const tableWidth = columnWidths.reduce((sum, width) => sum + width, 0)
    const startX = this.margin

    // Draw header row
    this.currentPage.drawRectangle({
      x: startX,
      y: this.yPosition - 20,
      width: tableWidth,
      height: 20,
      color: rgb(0.9, 0.9, 0.9),
      borderColor: rgb(0.5, 0.5, 0.5),
      borderWidth: 1
    })

    let xPos = startX + 5
    tableHeaders.forEach((header, index) => {
      this.currentPage.drawText(header, {
        x: xPos,
        y: this.yPosition - 15,
        size: 9,
        font: this.boldFont
      })
      xPos += columnWidths[index]
    })

    this.yPosition -= 25

    // Draw custody chain entries
    data.evidence.custodyChain.forEach((entry, index) => {
      this.checkPageSpace(25)

      const rowColor = index % 2 === 0 ? rgb(1, 1, 1) : rgb(0.98, 0.98, 0.98)

      this.currentPage.drawRectangle({
        x: startX,
        y: this.yPosition - 20,
        width: tableWidth,
        height: 20,
        color: rowColor,
        borderColor: rgb(0.7, 0.7, 0.7),
        borderWidth: 0.5
      })

      const rowData = [
        new Date(entry.timestamp).toLocaleString(),
        entry.officer,
        entry.action,
        entry.location || 'N/A',
        entry.notes || 'N/A'
      ]

      xPos = startX + 5
      rowData.forEach((data, colIndex) => {
        // Truncate text if too long
        const maxLength = Math.floor(columnWidths[colIndex] / 6)
        const displayText = data.length > maxLength ? 
          data.substring(0, maxLength - 3) + '...' : data

        this.currentPage.drawText(displayText, {
          x: xPos,
          y: this.yPosition - 15,
          size: 8,
          font: this.bodyFont
        })
        xPos += columnWidths[colIndex]
      })

      this.yPosition -= 25
    })

    this.yPosition -= 20
  }

  private drawIntegritySection(data: CustodyReportData): void {
    this.checkPageSpace(100)

    this.currentPage.drawText('INTEGRITY VERIFICATION', {
      x: this.margin,
      y: this.yPosition,
      size: 14,
      font: this.boldFont
    })

    this.yPosition -= 25

    const integrityInfo = [
      `File Hash: ${data.evidence.fileHash}`,
      `IPFS Content ID: ${data.evidence.ipfsCid}`,
      data.merkleRoot ? `Case Merkle Root: ${data.merkleRoot}` : 'Merkle Root: Not Available',
      `Custody Chain Entries: ${data.evidence.custodyChain.length}`,
      `Document Generated: ${new Date(data.generatedAt).toLocaleString()}`,
      `Generated By: ${data.generatedBy.name} (${data.generatedBy.email})`
    ]

    integrityInfo.forEach((info) => {
      this.currentPage.drawText(info, {
        x: this.margin,
        y: this.yPosition,
        size: 10,
        font: this.bodyFont
      })
      this.yPosition -= 15
    })

    this.yPosition -= 30

    // Legal disclaimer
    this.currentPage.drawText('LEGAL CERTIFICATION', {
      x: this.margin,
      y: this.yPosition,
      size: 12,
      font: this.boldFont
    })

    this.yPosition -= 20

    const disclaimer = [
      'This document represents the complete chain of custody for the referenced evidence item.',
      'All timestamps are recorded in UTC. File integrity is cryptographically verified through',
      'SHA-256 hashing and IPFS content addressing. Any tampering with the original evidence',
      'file would result in a different hash value. This report is generated automatically',
      'and contains no human-introduced errors in the custody timeline.'
    ]

    disclaimer.forEach((line) => {
      this.currentPage.drawText(line, {
        x: this.margin,
        y: this.yPosition,
        size: 9,
        font: this.bodyFont,
        color: rgb(0.3, 0.3, 0.3)
      })
      this.yPosition -= 12
    })
  }

  async generateCustodyReport(data: CustodyReportData): Promise<Uint8Array> {
    await this.initializePDF()

    this.drawHeader(data)
    this.drawEvidenceDetails(data)
    this.drawCustodyChainTable(data)
    this.drawIntegritySection(data)

    // Add footer to all pages
    this.doc.getPages().forEach(() => {
      this.addPageFooter()
    })

    return await this.doc.save()
  }
}

export async function generateCustodyChainPDF(data: CustodyReportData): Promise<Uint8Array> {
  const generator = new CustodyChainPDFGenerator()
  return await generator.generateCustodyReport(data)
}