import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { generateCustodyChainPDF } from '@/lib/pdf-generator'
import { updateCustodyChain } from '@/lib/custody-manager'
import { randomUUID } from 'crypto'

interface CustodyEntry {
  officer: string
  timestamp: string
  action: string
  ipfsCid: string
  notes?: string
  location?: string
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ evidenceId: string }> }
) {
  try {
    // Authenticate user
    const session = await getServerSession(authOptions)
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { evidenceId } = await params

    // Fetch evidence with related case and user data
    const evidence = await prisma.evidence.findUnique({
      where: { id: evidenceId },
      include: {
        case: {
          include: {
            User: {
              select: {
                name: true,
                email: true
              }
            }
          }
        }
      }
    })

    if (!evidence) {
      return NextResponse.json({ error: 'Evidence not found' }, { status: 404 })
    }

    // Check if user has access to the case
    const userHasAccess = await prisma.case.findFirst({
      where: {
        id: evidence.caseId,
        OR: [
          { User: { email: session.user.email } },
          // Add additional access checks here if needed (e.g., team members)
        ]
      }
    })

    if (!userHasAccess) {
      return NextResponse.json({ error: 'Access denied to this case' }, { status: 403 })
    }

    // Parse custody chain from JSON
    let custodyChain: CustodyEntry[] = []
    try {
      if (evidence.custodyChain) {
        custodyChain = typeof evidence.custodyChain === 'string' 
          ? JSON.parse(evidence.custodyChain) 
          : evidence.custodyChain as unknown as CustodyEntry[]
      }
    } catch (error) {
      console.error('Error parsing custody chain:', error)
      // Create a basic custody entry if parsing fails
      custodyChain = [{
        officer: evidence.collectedBy || 'Unknown',
        timestamp: evidence.collectedAt?.toISOString() || new Date().toISOString(),
        action: 'INITIAL_UPLOAD',
        ipfsCid: evidence.ipfsCid || 'N/A',
        location: evidence.location || undefined
      }]
    }

    // Fetch case merkle root if available
    let merkleRoot: string | undefined
    try {
      if (evidence.case.merkleRoot) {
        merkleRoot = evidence.case.merkleRoot
      }
    } catch (error) {
      console.error('Error fetching merkle root:', error)
    }

    // Get current user info for "generated by"
    const currentUser = await prisma.user.findUnique({
      where: { email: session.user.email },
      select: { name: true, email: true }
    })

    if (!currentUser) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 })
    }

    // Prepare data for PDF generation
    const reportData = {
      evidence: {
        id: evidence.id,
        title: evidence.filename, // Using filename as title since Evidence doesn't have title field
        description: evidence.notes || 'No description provided',
        filename: evidence.filename,
        fileHash: evidence.fileHash,
        ipfsCid: evidence.ipfsCid || 'N/A',
        collectedBy: evidence.collectedBy || 'Unknown',
        collectedAt: evidence.collectedAt?.toISOString() || new Date().toISOString(),
        location: evidence.location || undefined,
        custodyChain: custodyChain
      },
      case: {
        id: evidence.case.id,
        title: evidence.case.title,
        caseNumber: evidence.case.id, // Using ID as case number for now
        status: evidence.case.status,
        priority: evidence.case.priority,
        createdAt: evidence.case.createdAt.toISOString(),
        createdBy: {
          name: evidence.case.User.name || 'Unknown',
          email: evidence.case.User.email
        }
      },
      merkleRoot: merkleRoot,
      generatedAt: new Date().toISOString(),
      generatedBy: {
        name: currentUser.name || 'Unknown',
        email: currentUser.email
      }
    }

    // Generate PDF
    const pdfBytes = await generateCustodyChainPDF(reportData)

    // Log the PDF generation activity
    try {
      await prisma.activity.create({
        data: {
          id: randomUUID(),
          type: 'CUSTODY_REPORT_GENERATED',
          title: `Custody report generated for evidence: ${evidence.filename}`,
          description: `PDF custody chain report generated for case ${evidence.case.title}`,
          userId: currentUser.email,
          caseId: evidence.caseId,
          evidenceId: evidence.id
        }
      })
    } catch (error) {
      console.error('Error logging activity:', error)
      // Don't fail the request if logging fails
    }

    // Update custody chain for PDF generation
    try {
      await updateCustodyChain(
        evidenceId,
        currentUser.email,
        'CUSTODY_REPORT_GENERATED',
        `Custody chain PDF report generated for evidence ${evidence.filename}`
      )
    } catch (error) {
      console.error('Error updating custody chain:', error)
      // Don't fail the request if custody update fails
    }

    // Return PDF as response
    const filename = `custody-report-${evidence.filename}-${new Date().toISOString().split('T')[0]}.pdf`
    
    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': pdfBytes.length.toString(),
        'Cache-Control': 'no-cache, no-store, must-revalidate'
      }
    })

  } catch (error) {
    console.error('Error generating custody report:', error)
    return NextResponse.json(
      { 
        error: 'Failed to generate custody report',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}